CREATE TABLE known_birthdates (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birth_date_epoch INT NOT NULL,
    times_seen INT NOT NULL,
    tweeted SMALLINT NOT NULL,
    PRIMARY KEY (id)
);
