name: deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "projects/greg-finley/locations/us-central1/functions/check-oldest-living-person"
          runtime: "python311"
          entry_point: "main"
          memory_mb: 512
          secret_environment_variables: "MYSQL_CONFIG=projects/greg-finley/secrets/MYSQL_CONFIG/versions/latest"
          event_trigger_type: "providers/cloud.pubsub/eventTypes/topic.publish"
          event_trigger_resource: "projects/greg-finley/topics/oldest-living-person"
          event_trigger_service: "pubsub.googleapis.com"
          timeout: 60
          min_instances: 0
          max_instances: 1
